language: python

python:
  - "3.7"

# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - nosetests
  - coverage run --source=flask_rbac setup.py -q nosetests

after_success:
  - coveralls
